# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chessboard.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(800, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(800, 1000))
        MainWindow.setStyleSheet("background-color: rgb(64, 59, 65);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 10, 721, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.columns = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.columns.setContentsMargins(0, 0, 0, 0)
        self.columns.setObjectName("columns")
        self.A = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.A.setAlignment(QtCore.Qt.AlignCenter)
        self.A.setObjectName("A")
        self.columns.addWidget(self.A)
        self.B = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.B.setAlignment(QtCore.Qt.AlignCenter)
        self.B.setObjectName("B")
        self.columns.addWidget(self.B)
        self.C = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.C.setAlignment(QtCore.Qt.AlignCenter)
        self.C.setObjectName("C")
        self.columns.addWidget(self.C)
        self.D = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.D.setAlignment(QtCore.Qt.AlignCenter)
        self.D.setObjectName("D")
        self.columns.addWidget(self.D)
        self.E = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.E.setAlignment(QtCore.Qt.AlignCenter)
        self.E.setObjectName("E")
        self.columns.addWidget(self.E)
        self.F = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.F.setAlignment(QtCore.Qt.AlignCenter)
        self.F.setObjectName("F")
        self.columns.addWidget(self.F)
        self.G = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.G.setAlignment(QtCore.Qt.AlignCenter)
        self.G.setObjectName("G")
        self.columns.addWidget(self.G)
        self.H = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.H.setAlignment(QtCore.Qt.AlignCenter)
        self.H.setObjectName("H")
        self.columns.addWidget(self.H)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 51, 721))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.rows = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.rows.setContentsMargins(0, 0, 0, 0)
        self.rows.setObjectName("rows")
        self.v1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v1.setAlignment(QtCore.Qt.AlignCenter)
        self.v1.setObjectName("v1")
        self.rows.addWidget(self.v1)
        self.v2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v2.setAlignment(QtCore.Qt.AlignCenter)
        self.v2.setObjectName("v2")
        self.rows.addWidget(self.v2)
        self.v3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v3.setAlignment(QtCore.Qt.AlignCenter)
        self.v3.setObjectName("v3")
        self.rows.addWidget(self.v3)
        self.v4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v4.setAlignment(QtCore.Qt.AlignCenter)
        self.v4.setObjectName("v4")
        self.rows.addWidget(self.v4)
        self.v5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v5.setAlignment(QtCore.Qt.AlignCenter)
        self.v5.setObjectName("v5")
        self.rows.addWidget(self.v5)
        self.v6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v6.setAlignment(QtCore.Qt.AlignCenter)
        self.v6.setObjectName("v6")
        self.rows.addWidget(self.v6)
        self.v7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v7.setAlignment(QtCore.Qt.AlignCenter)
        self.v7.setObjectName("v7")
        self.rows.addWidget(self.v7)
        self.v8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v8.setAlignment(QtCore.Qt.AlignCenter)
        self.v8.setObjectName("v8")
        self.rows.addWidget(self.v8)
        self.moving = QtWidgets.QPushButton(self.centralwidget)
        self.moving.setGeometry(QtCore.QRect(-100, -100, 90, 90))
        self.moving.setStyleSheet("background: transparent;")
        self.moving.setText("")
        self.moving.setIconSize(QtCore.QSize(60, 60))
        self.moving.setObjectName("moving")
        self.text = QtWidgets.QLabel(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(20, 800, 761, 131))
        self.text.setObjectName("text")
        self.yes = QtWidgets.QPushButton(self.centralwidget)
        self.yes.setGeometry(QtCore.QRect(280, -100, 100, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.yes.setFont(font)
        self.yes.setStyleSheet("color: lime;")
        self.yes.setFlat(False)
        self.yes.setObjectName("yes")
        self.no = QtWidgets.QPushButton(self.centralwidget)
        self.no.setGeometry(QtCore.QRect(420, -100, 100, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.no.setFont(font)
        self.no.setStyleSheet("color: red;")
        self.no.setFlat(False)
        self.no.setObjectName("no")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.A.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">A</span></p></body></html>"))
        self.B.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">B</span></p></body></html>"))
        self.C.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">C</span></p></body></html>"))
        self.D.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">D</span></p></body></html>"))
        self.E.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">E</span></p></body></html>"))
        self.F.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">F</span></p></body></html>"))
        self.G.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">G</span></p></body></html>"))
        self.H.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">H</span></p></body></html>"))
        self.v1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">1</span></p></body></html>"))
        self.v2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">2</span></p></body></html>"))
        self.v3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">3</span></p></body></html>"))
        self.v4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">4</span></p></body></html>"))
        self.v5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">5</span></p></body></html>"))
        self.v6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">6</span></p></body></html>"))
        self.v7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">7</span></p></body></html>"))
        self.v8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">8</span></p></body></html>"))
        self.text.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ffffff;\"/></p></body></html>"))
        self.yes.setText(_translate("MainWindow", "Yes"))
        self.no.setText(_translate("MainWindow", "No"))
import resource_rc
