# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chessboard.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 800))
        MainWindow.setStyleSheet("background-color: rgb(64, 59, 65);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 10, 721, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.columns = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.columns.setContentsMargins(0, 0, 0, 0)
        self.columns.setObjectName("columns")
        self.A = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.A.setAlignment(QtCore.Qt.AlignCenter)
        self.A.setObjectName("A")
        self.columns.addWidget(self.A)
        self.B = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.B.setAlignment(QtCore.Qt.AlignCenter)
        self.B.setObjectName("B")
        self.columns.addWidget(self.B)
        self.C = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.C.setAlignment(QtCore.Qt.AlignCenter)
        self.C.setObjectName("C")
        self.columns.addWidget(self.C)
        self.D = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.D.setAlignment(QtCore.Qt.AlignCenter)
        self.D.setObjectName("D")
        self.columns.addWidget(self.D)
        self.E = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.E.setAlignment(QtCore.Qt.AlignCenter)
        self.E.setObjectName("E")
        self.columns.addWidget(self.E)
        self.F = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.F.setAlignment(QtCore.Qt.AlignCenter)
        self.F.setObjectName("F")
        self.columns.addWidget(self.F)
        self.G = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.G.setAlignment(QtCore.Qt.AlignCenter)
        self.G.setObjectName("G")
        self.columns.addWidget(self.G)
        self.H = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.H.setAlignment(QtCore.Qt.AlignCenter)
        self.H.setObjectName("H")
        self.columns.addWidget(self.H)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 60, 51, 721))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.rows = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.rows.setContentsMargins(0, 0, 0, 0)
        self.rows.setObjectName("rows")
        self.v1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v1.setAlignment(QtCore.Qt.AlignCenter)
        self.v1.setObjectName("v1")
        self.rows.addWidget(self.v1)
        self.v2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v2.setAlignment(QtCore.Qt.AlignCenter)
        self.v2.setObjectName("v2")
        self.rows.addWidget(self.v2)
        self.v3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v3.setAlignment(QtCore.Qt.AlignCenter)
        self.v3.setObjectName("v3")
        self.rows.addWidget(self.v3)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.rows.addWidget(self.label_14)
        self.v5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v5.setAlignment(QtCore.Qt.AlignCenter)
        self.v5.setObjectName("v5")
        self.rows.addWidget(self.v5)
        self.v6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v6.setAlignment(QtCore.Qt.AlignCenter)
        self.v6.setObjectName("v6")
        self.rows.addWidget(self.v6)
        self.v7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v7.setAlignment(QtCore.Qt.AlignCenter)
        self.v7.setObjectName("v7")
        self.rows.addWidget(self.v7)
        self.v8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.v8.setAlignment(QtCore.Qt.AlignCenter)
        self.v8.setObjectName("v8")
        self.rows.addWidget(self.v8)
        self.moving = QtWidgets.QPushButton(self.centralwidget)
        self.moving.setGeometry(QtCore.QRect(-100, -100, 90, 90))
        self.moving.setStyleSheet("background: transparent;")
        self.moving.setText("")
        self.moving.setIconSize(QtCore.QSize(60, 60))
        self.moving.setObjectName("moving")
        self.E5 = QtWidgets.QPushButton(self.centralwidget)
        self.E5.setGeometry(QtCore.QRect(660, 420, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E5.sizePolicy().hasHeightForWidth())
        self.E5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.E5.setFont(font)
        self.E5.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.E5.setText("")
        self.E5.setIconSize(QtCore.QSize(60, 60))
        self.E5.setCheckable(False)
        self.E5.setDefault(False)
        self.E5.setFlat(False)
        self.E5.setObjectName("E5")
        self.D7 = QtWidgets.QPushButton(self.centralwidget)
        self.D7.setGeometry(QtCore.QRect(570, 600, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D7.sizePolicy().hasHeightForWidth())
        self.D7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.D7.setFont(font)
        self.D7.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.D7.setText("")
        self.D7.setIconSize(QtCore.QSize(60, 60))
        self.D7.setCheckable(False)
        self.D7.setDefault(False)
        self.D7.setFlat(False)
        self.D7.setObjectName("D7")
        self.C8 = QtWidgets.QPushButton(self.centralwidget)
        self.C8.setGeometry(QtCore.QRect(480, 690, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C8.sizePolicy().hasHeightForWidth())
        self.C8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.C8.setFont(font)
        self.C8.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.C8.setText("")
        self.C8.setIconSize(QtCore.QSize(60, 60))
        self.C8.setCheckable(False)
        self.C8.setDefault(False)
        self.C8.setFlat(False)
        self.C8.setObjectName("C8")
        self.H7 = QtWidgets.QPushButton(self.centralwidget)
        self.H7.setGeometry(QtCore.QRect(930, 600, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H7.sizePolicy().hasHeightForWidth())
        self.H7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.H7.setFont(font)
        self.H7.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.H7.setText("")
        self.H7.setIconSize(QtCore.QSize(60, 60))
        self.H7.setCheckable(False)
        self.H7.setDefault(False)
        self.H7.setFlat(False)
        self.H7.setObjectName("H7")
        self.B7 = QtWidgets.QPushButton(self.centralwidget)
        self.B7.setGeometry(QtCore.QRect(390, 600, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B7.sizePolicy().hasHeightForWidth())
        self.B7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.B7.setFont(font)
        self.B7.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.B7.setText("")
        self.B7.setIconSize(QtCore.QSize(60, 60))
        self.B7.setCheckable(False)
        self.B7.setDefault(False)
        self.B7.setFlat(False)
        self.B7.setObjectName("B7")
        self.F1 = QtWidgets.QPushButton(self.centralwidget)
        self.F1.setGeometry(QtCore.QRect(750, 60, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F1.sizePolicy().hasHeightForWidth())
        self.F1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.F1.setFont(font)
        self.F1.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.F1.setText("")
        self.F1.setIconSize(QtCore.QSize(60, 60))
        self.F1.setCheckable(False)
        self.F1.setDefault(False)
        self.F1.setFlat(False)
        self.F1.setObjectName("F1")
        self.B6 = QtWidgets.QPushButton(self.centralwidget)
        self.B6.setGeometry(QtCore.QRect(390, 510, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B6.sizePolicy().hasHeightForWidth())
        self.B6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.B6.setFont(font)
        self.B6.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.B6.setText("")
        self.B6.setIconSize(QtCore.QSize(60, 60))
        self.B6.setCheckable(False)
        self.B6.setDefault(False)
        self.B6.setFlat(False)
        self.B6.setObjectName("B6")
        self.A1 = QtWidgets.QPushButton(self.centralwidget)
        self.A1.setGeometry(QtCore.QRect(300, 60, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A1.sizePolicy().hasHeightForWidth())
        self.A1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.A1.setFont(font)
        self.A1.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.A1.setText("")
        self.A1.setIconSize(QtCore.QSize(60, 60))
        self.A1.setCheckable(False)
        self.A1.setDefault(False)
        self.A1.setFlat(False)
        self.A1.setObjectName("A1")
        self.D6 = QtWidgets.QPushButton(self.centralwidget)
        self.D6.setGeometry(QtCore.QRect(570, 510, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D6.sizePolicy().hasHeightForWidth())
        self.D6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.D6.setFont(font)
        self.D6.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.D6.setText("")
        self.D6.setIconSize(QtCore.QSize(60, 60))
        self.D6.setCheckable(False)
        self.D6.setDefault(False)
        self.D6.setFlat(False)
        self.D6.setObjectName("D6")
        self.H4 = QtWidgets.QPushButton(self.centralwidget)
        self.H4.setGeometry(QtCore.QRect(930, 330, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H4.sizePolicy().hasHeightForWidth())
        self.H4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.H4.setFont(font)
        self.H4.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.H4.setText("")
        self.H4.setIconSize(QtCore.QSize(60, 60))
        self.H4.setCheckable(False)
        self.H4.setDefault(False)
        self.H4.setFlat(False)
        self.H4.setObjectName("H4")
        self.C6 = QtWidgets.QPushButton(self.centralwidget)
        self.C6.setGeometry(QtCore.QRect(480, 510, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C6.sizePolicy().hasHeightForWidth())
        self.C6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.C6.setFont(font)
        self.C6.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.C6.setText("")
        self.C6.setIconSize(QtCore.QSize(60, 60))
        self.C6.setCheckable(False)
        self.C6.setDefault(False)
        self.C6.setFlat(False)
        self.C6.setObjectName("C6")
        self.H1 = QtWidgets.QPushButton(self.centralwidget)
        self.H1.setGeometry(QtCore.QRect(930, 60, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H1.sizePolicy().hasHeightForWidth())
        self.H1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.H1.setFont(font)
        self.H1.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.H1.setText("")
        self.H1.setIconSize(QtCore.QSize(60, 60))
        self.H1.setCheckable(False)
        self.H1.setDefault(False)
        self.H1.setFlat(False)
        self.H1.setObjectName("H1")
        self.H3 = QtWidgets.QPushButton(self.centralwidget)
        self.H3.setGeometry(QtCore.QRect(930, 240, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H3.sizePolicy().hasHeightForWidth())
        self.H3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.H3.setFont(font)
        self.H3.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.H3.setText("")
        self.H3.setIconSize(QtCore.QSize(60, 60))
        self.H3.setCheckable(False)
        self.H3.setDefault(False)
        self.H3.setFlat(False)
        self.H3.setObjectName("H3")
        self.H5 = QtWidgets.QPushButton(self.centralwidget)
        self.H5.setGeometry(QtCore.QRect(930, 420, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H5.sizePolicy().hasHeightForWidth())
        self.H5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.H5.setFont(font)
        self.H5.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.H5.setText("")
        self.H5.setIconSize(QtCore.QSize(60, 60))
        self.H5.setCheckable(False)
        self.H5.setDefault(False)
        self.H5.setFlat(False)
        self.H5.setObjectName("H5")
        self.G2 = QtWidgets.QPushButton(self.centralwidget)
        self.G2.setGeometry(QtCore.QRect(840, 150, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G2.sizePolicy().hasHeightForWidth())
        self.G2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.G2.setFont(font)
        self.G2.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.G2.setText("")
        self.G2.setIconSize(QtCore.QSize(60, 60))
        self.G2.setCheckable(False)
        self.G2.setDefault(False)
        self.G2.setFlat(False)
        self.G2.setObjectName("G2")
        self.E6 = QtWidgets.QPushButton(self.centralwidget)
        self.E6.setGeometry(QtCore.QRect(660, 510, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E6.sizePolicy().hasHeightForWidth())
        self.E6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.E6.setFont(font)
        self.E6.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.E6.setText("")
        self.E6.setIconSize(QtCore.QSize(60, 60))
        self.E6.setCheckable(False)
        self.E6.setDefault(False)
        self.E6.setFlat(False)
        self.E6.setObjectName("E6")
        self.E8 = QtWidgets.QPushButton(self.centralwidget)
        self.E8.setGeometry(QtCore.QRect(660, 690, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E8.sizePolicy().hasHeightForWidth())
        self.E8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.E8.setFont(font)
        self.E8.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.E8.setText("")
        self.E8.setIconSize(QtCore.QSize(60, 60))
        self.E8.setCheckable(False)
        self.E8.setDefault(False)
        self.E8.setFlat(False)
        self.E8.setObjectName("E8")
        self.F8 = QtWidgets.QPushButton(self.centralwidget)
        self.F8.setGeometry(QtCore.QRect(750, 690, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F8.sizePolicy().hasHeightForWidth())
        self.F8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.F8.setFont(font)
        self.F8.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.F8.setText("")
        self.F8.setIconSize(QtCore.QSize(60, 60))
        self.F8.setCheckable(False)
        self.F8.setDefault(False)
        self.F8.setFlat(False)
        self.F8.setObjectName("F8")
        self.B8 = QtWidgets.QPushButton(self.centralwidget)
        self.B8.setGeometry(QtCore.QRect(390, 690, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B8.sizePolicy().hasHeightForWidth())
        self.B8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.B8.setFont(font)
        self.B8.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.B8.setText("")
        self.B8.setIconSize(QtCore.QSize(60, 60))
        self.B8.setCheckable(False)
        self.B8.setDefault(False)
        self.B8.setFlat(False)
        self.B8.setObjectName("B8")
        self.H8 = QtWidgets.QPushButton(self.centralwidget)
        self.H8.setGeometry(QtCore.QRect(930, 690, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H8.sizePolicy().hasHeightForWidth())
        self.H8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.H8.setFont(font)
        self.H8.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.H8.setText("")
        self.H8.setIconSize(QtCore.QSize(60, 60))
        self.H8.setCheckable(False)
        self.H8.setDefault(False)
        self.H8.setFlat(False)
        self.H8.setObjectName("H8")
        self.G8 = QtWidgets.QPushButton(self.centralwidget)
        self.G8.setGeometry(QtCore.QRect(840, 690, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G8.sizePolicy().hasHeightForWidth())
        self.G8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.G8.setFont(font)
        self.G8.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.G8.setText("")
        self.G8.setIconSize(QtCore.QSize(60, 60))
        self.G8.setCheckable(False)
        self.G8.setDefault(False)
        self.G8.setFlat(False)
        self.G8.setObjectName("G8")
        self.D8 = QtWidgets.QPushButton(self.centralwidget)
        self.D8.setGeometry(QtCore.QRect(570, 690, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D8.sizePolicy().hasHeightForWidth())
        self.D8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.D8.setFont(font)
        self.D8.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.D8.setText("")
        self.D8.setIconSize(QtCore.QSize(60, 60))
        self.D8.setCheckable(False)
        self.D8.setDefault(False)
        self.D8.setFlat(False)
        self.D8.setObjectName("D8")
        self.A8 = QtWidgets.QPushButton(self.centralwidget)
        self.A8.setGeometry(QtCore.QRect(300, 690, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A8.sizePolicy().hasHeightForWidth())
        self.A8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.A8.setFont(font)
        self.A8.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.A8.setText("")
        self.A8.setIconSize(QtCore.QSize(60, 60))
        self.A8.setCheckable(False)
        self.A8.setDefault(False)
        self.A8.setFlat(False)
        self.A8.setObjectName("A8")
        self.A7 = QtWidgets.QPushButton(self.centralwidget)
        self.A7.setGeometry(QtCore.QRect(300, 600, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A7.sizePolicy().hasHeightForWidth())
        self.A7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.A7.setFont(font)
        self.A7.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.A7.setText("")
        self.A7.setIconSize(QtCore.QSize(60, 60))
        self.A7.setCheckable(False)
        self.A7.setDefault(False)
        self.A7.setFlat(False)
        self.A7.setObjectName("A7")
        self.F6 = QtWidgets.QPushButton(self.centralwidget)
        self.F6.setGeometry(QtCore.QRect(750, 510, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F6.sizePolicy().hasHeightForWidth())
        self.F6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.F6.setFont(font)
        self.F6.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.F6.setText("")
        self.F6.setIconSize(QtCore.QSize(60, 60))
        self.F6.setCheckable(False)
        self.F6.setDefault(False)
        self.F6.setFlat(False)
        self.F6.setObjectName("F6")
        self.B1 = QtWidgets.QPushButton(self.centralwidget)
        self.B1.setGeometry(QtCore.QRect(390, 60, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B1.sizePolicy().hasHeightForWidth())
        self.B1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.B1.setFont(font)
        self.B1.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.B1.setText("")
        self.B1.setIconSize(QtCore.QSize(60, 60))
        self.B1.setCheckable(False)
        self.B1.setDefault(False)
        self.B1.setFlat(False)
        self.B1.setObjectName("B1")
        self.G7 = QtWidgets.QPushButton(self.centralwidget)
        self.G7.setGeometry(QtCore.QRect(840, 600, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G7.sizePolicy().hasHeightForWidth())
        self.G7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.G7.setFont(font)
        self.G7.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.G7.setText("")
        self.G7.setIconSize(QtCore.QSize(60, 60))
        self.G7.setCheckable(False)
        self.G7.setDefault(False)
        self.G7.setFlat(False)
        self.G7.setObjectName("G7")
        self.F5 = QtWidgets.QPushButton(self.centralwidget)
        self.F5.setGeometry(QtCore.QRect(750, 420, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F5.sizePolicy().hasHeightForWidth())
        self.F5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.F5.setFont(font)
        self.F5.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.F5.setText("")
        self.F5.setIconSize(QtCore.QSize(60, 60))
        self.F5.setCheckable(False)
        self.F5.setDefault(False)
        self.F5.setFlat(False)
        self.F5.setObjectName("F5")
        self.H6 = QtWidgets.QPushButton(self.centralwidget)
        self.H6.setGeometry(QtCore.QRect(930, 510, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H6.sizePolicy().hasHeightForWidth())
        self.H6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.H6.setFont(font)
        self.H6.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.H6.setText("")
        self.H6.setIconSize(QtCore.QSize(60, 60))
        self.H6.setCheckable(False)
        self.H6.setDefault(False)
        self.H6.setFlat(False)
        self.H6.setObjectName("H6")
        self.G1 = QtWidgets.QPushButton(self.centralwidget)
        self.G1.setGeometry(QtCore.QRect(840, 60, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G1.sizePolicy().hasHeightForWidth())
        self.G1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.G1.setFont(font)
        self.G1.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.G1.setText("")
        self.G1.setIconSize(QtCore.QSize(60, 60))
        self.G1.setCheckable(False)
        self.G1.setDefault(False)
        self.G1.setFlat(False)
        self.G1.setObjectName("G1")
        self.A5 = QtWidgets.QPushButton(self.centralwidget)
        self.A5.setGeometry(QtCore.QRect(300, 420, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A5.sizePolicy().hasHeightForWidth())
        self.A5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.A5.setFont(font)
        self.A5.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.A5.setText("")
        self.A5.setIconSize(QtCore.QSize(60, 60))
        self.A5.setCheckable(False)
        self.A5.setDefault(False)
        self.A5.setFlat(False)
        self.A5.setObjectName("A5")
        self.G5 = QtWidgets.QPushButton(self.centralwidget)
        self.G5.setGeometry(QtCore.QRect(840, 420, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G5.sizePolicy().hasHeightForWidth())
        self.G5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.G5.setFont(font)
        self.G5.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.G5.setText("")
        self.G5.setIconSize(QtCore.QSize(60, 60))
        self.G5.setCheckable(False)
        self.G5.setDefault(False)
        self.G5.setFlat(False)
        self.G5.setObjectName("G5")
        self.G6 = QtWidgets.QPushButton(self.centralwidget)
        self.G6.setGeometry(QtCore.QRect(840, 510, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G6.sizePolicy().hasHeightForWidth())
        self.G6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.G6.setFont(font)
        self.G6.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.G6.setText("")
        self.G6.setIconSize(QtCore.QSize(60, 60))
        self.G6.setCheckable(False)
        self.G6.setDefault(False)
        self.G6.setFlat(False)
        self.G6.setObjectName("G6")
        self.B3 = QtWidgets.QPushButton(self.centralwidget)
        self.B3.setGeometry(QtCore.QRect(390, 240, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B3.sizePolicy().hasHeightForWidth())
        self.B3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.B3.setFont(font)
        self.B3.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.B3.setText("")
        self.B3.setIconSize(QtCore.QSize(60, 60))
        self.B3.setCheckable(False)
        self.B3.setDefault(False)
        self.B3.setFlat(False)
        self.B3.setObjectName("B3")
        self.H2 = QtWidgets.QPushButton(self.centralwidget)
        self.H2.setGeometry(QtCore.QRect(930, 150, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.H2.sizePolicy().hasHeightForWidth())
        self.H2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.H2.setFont(font)
        self.H2.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.H2.setText("")
        self.H2.setIconSize(QtCore.QSize(60, 60))
        self.H2.setCheckable(False)
        self.H2.setDefault(False)
        self.H2.setFlat(False)
        self.H2.setObjectName("H2")
        self.D5 = QtWidgets.QPushButton(self.centralwidget)
        self.D5.setGeometry(QtCore.QRect(570, 420, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5.sizePolicy().hasHeightForWidth())
        self.D5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.D5.setFont(font)
        self.D5.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.D5.setText("")
        self.D5.setIconSize(QtCore.QSize(60, 60))
        self.D5.setCheckable(False)
        self.D5.setDefault(False)
        self.D5.setFlat(False)
        self.D5.setObjectName("D5")
        self.F4 = QtWidgets.QPushButton(self.centralwidget)
        self.F4.setGeometry(QtCore.QRect(750, 330, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F4.sizePolicy().hasHeightForWidth())
        self.F4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.F4.setFont(font)
        self.F4.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.F4.setText("")
        self.F4.setIconSize(QtCore.QSize(60, 60))
        self.F4.setCheckable(False)
        self.F4.setDefault(False)
        self.F4.setFlat(False)
        self.F4.setObjectName("F4")
        self.G3 = QtWidgets.QPushButton(self.centralwidget)
        self.G3.setGeometry(QtCore.QRect(840, 240, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G3.sizePolicy().hasHeightForWidth())
        self.G3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.G3.setFont(font)
        self.G3.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.G3.setText("")
        self.G3.setIconSize(QtCore.QSize(60, 60))
        self.G3.setCheckable(False)
        self.G3.setDefault(False)
        self.G3.setFlat(False)
        self.G3.setObjectName("G3")
        self.F3 = QtWidgets.QPushButton(self.centralwidget)
        self.F3.setGeometry(QtCore.QRect(750, 240, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F3.sizePolicy().hasHeightForWidth())
        self.F3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.F3.setFont(font)
        self.F3.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.F3.setText("")
        self.F3.setIconSize(QtCore.QSize(60, 60))
        self.F3.setCheckable(False)
        self.F3.setDefault(False)
        self.F3.setFlat(False)
        self.F3.setObjectName("F3")
        self.B4 = QtWidgets.QPushButton(self.centralwidget)
        self.B4.setGeometry(QtCore.QRect(390, 330, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B4.sizePolicy().hasHeightForWidth())
        self.B4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.B4.setFont(font)
        self.B4.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.B4.setText("")
        self.B4.setIconSize(QtCore.QSize(60, 60))
        self.B4.setCheckable(False)
        self.B4.setDefault(False)
        self.B4.setFlat(False)
        self.B4.setObjectName("B4")
        self.B5 = QtWidgets.QPushButton(self.centralwidget)
        self.B5.setGeometry(QtCore.QRect(390, 420, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B5.sizePolicy().hasHeightForWidth())
        self.B5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.B5.setFont(font)
        self.B5.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.B5.setText("")
        self.B5.setIconSize(QtCore.QSize(60, 60))
        self.B5.setCheckable(False)
        self.B5.setDefault(False)
        self.B5.setFlat(False)
        self.B5.setObjectName("B5")
        self.C4 = QtWidgets.QPushButton(self.centralwidget)
        self.C4.setGeometry(QtCore.QRect(480, 330, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C4.sizePolicy().hasHeightForWidth())
        self.C4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.C4.setFont(font)
        self.C4.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.C4.setText("")
        self.C4.setIconSize(QtCore.QSize(60, 60))
        self.C4.setCheckable(False)
        self.C4.setDefault(False)
        self.C4.setFlat(False)
        self.C4.setObjectName("C4")
        self.C5 = QtWidgets.QPushButton(self.centralwidget)
        self.C5.setGeometry(QtCore.QRect(480, 420, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C5.sizePolicy().hasHeightForWidth())
        self.C5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.C5.setFont(font)
        self.C5.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.C5.setText("")
        self.C5.setIconSize(QtCore.QSize(60, 60))
        self.C5.setCheckable(False)
        self.C5.setDefault(False)
        self.C5.setFlat(False)
        self.C5.setObjectName("C5")
        self.E4 = QtWidgets.QPushButton(self.centralwidget)
        self.E4.setGeometry(QtCore.QRect(660, 330, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E4.sizePolicy().hasHeightForWidth())
        self.E4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.E4.setFont(font)
        self.E4.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.E4.setText("")
        self.E4.setIconSize(QtCore.QSize(60, 60))
        self.E4.setCheckable(False)
        self.E4.setDefault(False)
        self.E4.setFlat(False)
        self.E4.setObjectName("E4")
        self.E2 = QtWidgets.QPushButton(self.centralwidget)
        self.E2.setGeometry(QtCore.QRect(660, 150, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E2.sizePolicy().hasHeightForWidth())
        self.E2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.E2.setFont(font)
        self.E2.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.E2.setText("")
        self.E2.setIconSize(QtCore.QSize(60, 60))
        self.E2.setCheckable(False)
        self.E2.setDefault(False)
        self.E2.setFlat(False)
        self.E2.setObjectName("E2")
        self.A4 = QtWidgets.QPushButton(self.centralwidget)
        self.A4.setGeometry(QtCore.QRect(300, 330, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A4.sizePolicy().hasHeightForWidth())
        self.A4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.A4.setFont(font)
        self.A4.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.A4.setText("")
        self.A4.setIconSize(QtCore.QSize(60, 60))
        self.A4.setCheckable(False)
        self.A4.setDefault(False)
        self.A4.setFlat(False)
        self.A4.setObjectName("A4")
        self.F2 = QtWidgets.QPushButton(self.centralwidget)
        self.F2.setGeometry(QtCore.QRect(750, 150, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F2.sizePolicy().hasHeightForWidth())
        self.F2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.F2.setFont(font)
        self.F2.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.F2.setText("")
        self.F2.setIconSize(QtCore.QSize(60, 60))
        self.F2.setCheckable(False)
        self.F2.setDefault(False)
        self.F2.setFlat(False)
        self.F2.setObjectName("F2")
        self.G4 = QtWidgets.QPushButton(self.centralwidget)
        self.G4.setGeometry(QtCore.QRect(840, 330, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G4.sizePolicy().hasHeightForWidth())
        self.G4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.G4.setFont(font)
        self.G4.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.G4.setText("")
        self.G4.setIconSize(QtCore.QSize(60, 60))
        self.G4.setCheckable(False)
        self.G4.setDefault(False)
        self.G4.setFlat(False)
        self.G4.setObjectName("G4")
        self.D4 = QtWidgets.QPushButton(self.centralwidget)
        self.D4.setGeometry(QtCore.QRect(570, 330, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D4.sizePolicy().hasHeightForWidth())
        self.D4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.D4.setFont(font)
        self.D4.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.D4.setText("")
        self.D4.setIconSize(QtCore.QSize(60, 60))
        self.D4.setCheckable(False)
        self.D4.setDefault(False)
        self.D4.setFlat(False)
        self.D4.setObjectName("D4")
        self.A6 = QtWidgets.QPushButton(self.centralwidget)
        self.A6.setGeometry(QtCore.QRect(300, 510, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A6.sizePolicy().hasHeightForWidth())
        self.A6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.A6.setFont(font)
        self.A6.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.A6.setText("")
        self.A6.setIconSize(QtCore.QSize(60, 60))
        self.A6.setCheckable(False)
        self.A6.setDefault(False)
        self.A6.setFlat(False)
        self.A6.setObjectName("A6")
        self.C3 = QtWidgets.QPushButton(self.centralwidget)
        self.C3.setGeometry(QtCore.QRect(480, 240, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C3.sizePolicy().hasHeightForWidth())
        self.C3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.C3.setFont(font)
        self.C3.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.C3.setText("")
        self.C3.setIconSize(QtCore.QSize(60, 60))
        self.C3.setCheckable(False)
        self.C3.setDefault(False)
        self.C3.setFlat(False)
        self.C3.setObjectName("C3")
        self.D2 = QtWidgets.QPushButton(self.centralwidget)
        self.D2.setGeometry(QtCore.QRect(570, 150, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D2.sizePolicy().hasHeightForWidth())
        self.D2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.D2.setFont(font)
        self.D2.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.D2.setText("")
        self.D2.setIconSize(QtCore.QSize(60, 60))
        self.D2.setCheckable(False)
        self.D2.setDefault(False)
        self.D2.setFlat(False)
        self.D2.setObjectName("D2")
        self.D3 = QtWidgets.QPushButton(self.centralwidget)
        self.D3.setGeometry(QtCore.QRect(570, 240, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3.sizePolicy().hasHeightForWidth())
        self.D3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.D3.setFont(font)
        self.D3.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.D3.setText("")
        self.D3.setIconSize(QtCore.QSize(60, 60))
        self.D3.setCheckable(False)
        self.D3.setDefault(False)
        self.D3.setFlat(False)
        self.D3.setObjectName("D3")
        self.E7 = QtWidgets.QPushButton(self.centralwidget)
        self.E7.setGeometry(QtCore.QRect(660, 600, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E7.sizePolicy().hasHeightForWidth())
        self.E7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.E7.setFont(font)
        self.E7.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.E7.setText("")
        self.E7.setIconSize(QtCore.QSize(60, 60))
        self.E7.setCheckable(False)
        self.E7.setDefault(False)
        self.E7.setFlat(False)
        self.E7.setObjectName("E7")
        self.E3 = QtWidgets.QPushButton(self.centralwidget)
        self.E3.setGeometry(QtCore.QRect(660, 240, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E3.sizePolicy().hasHeightForWidth())
        self.E3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.E3.setFont(font)
        self.E3.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.E3.setText("")
        self.E3.setIconSize(QtCore.QSize(60, 60))
        self.E3.setCheckable(False)
        self.E3.setDefault(False)
        self.E3.setFlat(False)
        self.E3.setObjectName("E3")
        self.A3 = QtWidgets.QPushButton(self.centralwidget)
        self.A3.setGeometry(QtCore.QRect(300, 240, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A3.sizePolicy().hasHeightForWidth())
        self.A3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.A3.setFont(font)
        self.A3.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.A3.setText("")
        self.A3.setIconSize(QtCore.QSize(60, 60))
        self.A3.setCheckable(False)
        self.A3.setDefault(False)
        self.A3.setFlat(False)
        self.A3.setObjectName("A3")
        self.E1 = QtWidgets.QPushButton(self.centralwidget)
        self.E1.setGeometry(QtCore.QRect(660, 60, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.E1.sizePolicy().hasHeightForWidth())
        self.E1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.E1.setFont(font)
        self.E1.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.E1.setText("")
        self.E1.setIconSize(QtCore.QSize(60, 60))
        self.E1.setCheckable(False)
        self.E1.setDefault(False)
        self.E1.setFlat(False)
        self.E1.setObjectName("E1")
        self.F7 = QtWidgets.QPushButton(self.centralwidget)
        self.F7.setGeometry(QtCore.QRect(750, 600, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F7.sizePolicy().hasHeightForWidth())
        self.F7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.F7.setFont(font)
        self.F7.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.F7.setText("")
        self.F7.setIconSize(QtCore.QSize(60, 60))
        self.F7.setCheckable(False)
        self.F7.setDefault(False)
        self.F7.setFlat(False)
        self.F7.setObjectName("F7")
        self.B2 = QtWidgets.QPushButton(self.centralwidget)
        self.B2.setGeometry(QtCore.QRect(390, 150, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B2.sizePolicy().hasHeightForWidth())
        self.B2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.B2.setFont(font)
        self.B2.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.B2.setText("")
        self.B2.setIconSize(QtCore.QSize(60, 60))
        self.B2.setCheckable(False)
        self.B2.setDefault(False)
        self.B2.setFlat(False)
        self.B2.setObjectName("B2")
        self.C1 = QtWidgets.QPushButton(self.centralwidget)
        self.C1.setGeometry(QtCore.QRect(480, 60, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C1.sizePolicy().hasHeightForWidth())
        self.C1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.C1.setFont(font)
        self.C1.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.C1.setText("")
        self.C1.setIconSize(QtCore.QSize(60, 60))
        self.C1.setCheckable(False)
        self.C1.setDefault(False)
        self.C1.setFlat(False)
        self.C1.setObjectName("C1")
        self.C2 = QtWidgets.QPushButton(self.centralwidget)
        self.C2.setGeometry(QtCore.QRect(480, 150, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C2.sizePolicy().hasHeightForWidth())
        self.C2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.C2.setFont(font)
        self.C2.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.C2.setText("")
        self.C2.setIconSize(QtCore.QSize(60, 60))
        self.C2.setCheckable(False)
        self.C2.setDefault(False)
        self.C2.setFlat(False)
        self.C2.setObjectName("C2")
        self.C7 = QtWidgets.QPushButton(self.centralwidget)
        self.C7.setGeometry(QtCore.QRect(480, 600, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C7.sizePolicy().hasHeightForWidth())
        self.C7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.C7.setFont(font)
        self.C7.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(231, 231, 231, 255), stop:1 rgba(246, 251, 247, 255));")
        self.C7.setText("")
        self.C7.setIconSize(QtCore.QSize(60, 60))
        self.C7.setCheckable(False)
        self.C7.setDefault(False)
        self.C7.setFlat(False)
        self.C7.setObjectName("C7")
        self.D1 = QtWidgets.QPushButton(self.centralwidget)
        self.D1.setGeometry(QtCore.QRect(570, 60, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D1.sizePolicy().hasHeightForWidth())
        self.D1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.D1.setFont(font)
        self.D1.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.D1.setText("")
        self.D1.setIconSize(QtCore.QSize(60, 60))
        self.D1.setCheckable(False)
        self.D1.setDefault(False)
        self.D1.setFlat(False)
        self.D1.setObjectName("D1")
        self.A2 = QtWidgets.QPushButton(self.centralwidget)
        self.A2.setGeometry(QtCore.QRect(300, 150, 90, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A2.sizePolicy().hasHeightForWidth())
        self.A2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.A2.setFont(font)
        self.A2.setStyleSheet("border: 2px solid;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(123, 119, 120, 255), stop:1 rgba(125, 121, 122, 255));")
        self.A2.setText("")
        self.A2.setIconSize(QtCore.QSize(60, 60))
        self.A2.setCheckable(False)
        self.A2.setDefault(False)
        self.A2.setFlat(False)
        self.A2.setObjectName("A2")
        self.horizontalLayoutWidget.raise_()
        self.verticalLayoutWidget.raise_()
        self.E5.raise_()
        self.D7.raise_()
        self.C8.raise_()
        self.H7.raise_()
        self.B7.raise_()
        self.F1.raise_()
        self.B6.raise_()
        self.A1.raise_()
        self.D6.raise_()
        self.H4.raise_()
        self.C6.raise_()
        self.H1.raise_()
        self.H3.raise_()
        self.H5.raise_()
        self.G2.raise_()
        self.E6.raise_()
        self.E8.raise_()
        self.F8.raise_()
        self.B8.raise_()
        self.H8.raise_()
        self.G8.raise_()
        self.D8.raise_()
        self.A8.raise_()
        self.A7.raise_()
        self.F6.raise_()
        self.B1.raise_()
        self.G7.raise_()
        self.F5.raise_()
        self.H6.raise_()
        self.G1.raise_()
        self.A5.raise_()
        self.G5.raise_()
        self.G6.raise_()
        self.B3.raise_()
        self.H2.raise_()
        self.D5.raise_()
        self.F4.raise_()
        self.G3.raise_()
        self.F3.raise_()
        self.B4.raise_()
        self.B5.raise_()
        self.C4.raise_()
        self.C5.raise_()
        self.E4.raise_()
        self.E2.raise_()
        self.A4.raise_()
        self.F2.raise_()
        self.G4.raise_()
        self.D4.raise_()
        self.A6.raise_()
        self.C3.raise_()
        self.D2.raise_()
        self.D3.raise_()
        self.E7.raise_()
        self.E3.raise_()
        self.A3.raise_()
        self.E1.raise_()
        self.F7.raise_()
        self.B2.raise_()
        self.C1.raise_()
        self.C2.raise_()
        self.C7.raise_()
        self.D1.raise_()
        self.A2.raise_()
        self.moving.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.A.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">A</span></p></body></html>"))
        self.B.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">B</span></p></body></html>"))
        self.C.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">C</span></p></body></html>"))
        self.D.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">D</span></p></body></html>"))
        self.E.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">E</span></p></body></html>"))
        self.F.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">F</span></p></body></html>"))
        self.G.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">G</span></p></body></html>"))
        self.H.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">H</span></p></body></html>"))
        self.v1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">1</span></p></body></html>"))
        self.v2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">2</span></p></body></html>"))
        self.v3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">3</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">4</span></p></body></html>"))
        self.v5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">5</span></p></body></html>"))
        self.v6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">6</span></p></body></html>"))
        self.v7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">7</span></p></body></html>"))
        self.v8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; color:#ffffff;\">8</span></p></body></html>"))
import resource_rc
